In [41]:
import pandas as pd

traffic_2022 = pd.read_csv('Traffic_Volume_2022.csv')
traffic_2023 = pd.read_csv('Traffic_Volume_2023.csv')
traffic_2024 = pd.read_csv('Traffic_Volume_2024_January_to_May.csv')
weather_2022 = pd.read_csv('Weather_Indianapolis_2022.csv')
weather_2023 = pd.read_csv('Weather_Indianapolis_2023.csv')
weather_2024 = pd.read_csv('Weather_Indianapolis_2024_January_to_May.csv')

air_quality_2022 = pd.read_excel('Air_quality_index_2022.xlsx')
air_quality_2023 = pd.read_excel('Air_quality_index_2023.xlsx')
air_quality_2024 = pd.read_excel('Air_quality_index_2024_January_to_May.xlsx')

In [43]:
weather_2023.head(50)

          date  tavg  tmin  tmax  prcp  snow  wdir  wspd  wpgt    pres  tsun
0   2023-01-01   7.3   4.4  11.1   0.0     0   198  12.6   NaN  1015.1   NaN
1   2023-01-02  10.3   8.9  13.9   0.3     0   101   8.6   NaN  1015.6   NaN
2   2023-01-03  14.9  13.3  17.2  21.6     0   181  18.7   NaN  1005.5   NaN
3   2023-01-04  10.2   2.8  15.0   0.0     0   252  19.8   NaN  1008.3   NaN
4   2023-01-05   2.9   0.6   4.4   0.3     0   230  19.8   NaN  1014.3   NaN
5   2023-01-06   1.1  -2.1   3.9   0.0     0   249  15.1   NaN  1021.9   NaN
6   2023-01-07  -0.6  -4.3   3.9   0.0     0    32  11.9   NaN  1026.9   NaN
7   2023-01-08   0.6  -1.0   3.9   0.0     0    11  11.5   NaN  1023.2   NaN
8   2023-01-09   0.8  -1.6   6.7   0.0     0   226  13.3   NaN  1022.1   NaN
9   2023-01-10   4.2   0.6  11.1   0.0     0   184  11.2   NaN  1014.1   NaN
10  2023-01-11   6.3   3.9   9.4   0.3     0   141  11.5   NaN  1010.7   NaN
11  2023-01-12   7.6   2.2   9.4  22.1     0     5  25.2   NaN  1009.5   NaN
12  2023-01-13   1.4  -0.5   2.2   0.5     0   328  24.1   NaN  1020.0   NaN
13  2023-01-14  -1.2  -4.3   0.0   0.0     0   344  13.7   NaN  1025.4   NaN
14  2023-01-15  -1.6  -5.5   5.6   0.0     0   142  15.5   NaN  1022.4   NaN
15  2023-01-16   2.6   0.6  11.1   3.6     0   144  17.3   NaN  1010.3   NaN
16  2023-01-17   8.8   3.9  12.2   1.3     0   250  25.6   NaN  1005.6   NaN
17  2023-01-18   3.4   1.1   7.2  25.4     0    73  16.2   NaN  1013.2   NaN
18  2023-01-19   7.6   1.7  13.3   2.3     0   225  30.6   NaN  1003.4   NaN
19  2023-01-20   1.3  -1.0   1.7   0.0     0   275  25.9   NaN  1019.5   NaN
20  2023-01-21  -0.6  -1.0   0.6   0.0     0   214  10.4   NaN  1022.7   NaN
21  2023-01-22  -0.2  -2.1   1.1   1.0     0    15   9.4   NaN  1011.7   NaN
22  2023-01-23  -0.2  -2.7   0.6   0.0     0   267  18.4   NaN  1019.7   NaN
23  2023-01-24   0.4  -3.2   6.7   0.0     0   233  11.2   NaN  1022.8   NaN
24  2023-01-25   1.5   0.0   3.3  17.5    30   358  20.2   NaN  1006.4   NaN
25  2023-01-26  -1.2  -4.3   0.6   0.0    30   262  26.6   NaN  1015.6   NaN
26  2023-01-27  -2.7  -7.1   5.0   0.0    30   212  22.3   NaN  1016.8   NaN
27  2023-01-28   3.7  -1.6  11.7   1.0     0   193  14.8   NaN  1020.5   NaN
28  2023-01-29   4.9  -1.0   6.1   2.3     0   294  15.8   NaN  1020.1   NaN
29  2023-01-30  -1.7  -7.1  -1.0   1.5     0   349  16.9   NaN  1026.0   NaN
30  2023-01-31  -7.4 -10.5  -4.3   0.0     0   352  13.3   NaN  1029.3   NaN
31  2023-02-01  -7.2 -12.1  -1.6   0.0     0   337   5.0   NaN  1029.3   NaN
32  2023-02-02  -2.4  -7.1   4.4   0.0     0   238  19.8   NaN  1023.1   NaN
33  2023-02-03  -6.0 -11.0  -3.8   0.0     0   331  16.6   NaN  1033.1   NaN
34  2023-02-04  -4.2  -9.9   7.2   0.0     0   182  25.9   NaN  1026.5   NaN
35  2023-02-05   6.3   0.6  11.1   0.0     0   238  25.6   NaN  1016.6   NaN
36  2023-02-06   1.9  -3.2   7.8   0.0     0   112  15.1   NaN  1021.9   NaN
37  2023-02-07   9.2   1.1  14.4   0.0     0   233  19.4   NaN  1018.1   NaN
38  2023-02-08   3.6  -2.7  10.0  11.4     0   101   9.4   NaN  1022.9   NaN
39  2023-02-09   9.2   2.8  15.6  23.1     0   201  35.6   NaN  1008.7   NaN
40  2023-02-10   3.1  -2.1   6.1   0.0     0   280  16.2   NaN  1025.1   NaN
41  2023-02-11   0.3  -4.3   7.2   0.0     0    34   4.7   NaN  1028.1   NaN
42  2023-02-12   3.1  -4.9  12.8   0.0     0   345   6.8   NaN  1017.2   NaN
43  2023-02-13   5.9  -0.5  13.9   0.0     0   263  14.0   NaN  1011.9   NaN
44  2023-02-14   6.4   0.6  13.9   2.3     0   138  20.2   NaN  1010.2   NaN
45  2023-02-15  13.6   5.6  17.8   0.0     0   239  29.9   NaN  1009.6   NaN
46  2023-02-16   8.1   0.6  15.0   9.9     0    48  22.0   NaN  1009.9   NaN
47  2023-02-17   0.2  -5.5   0.6   0.0     0   306  22.7   NaN  1023.2   NaN
48  2023-02-18  -0.8  -6.6   9.4   0.0     0   204  20.2   NaN  1027.7   NaN
49  2023-02-19   7.3   3.3  14.4   0.0     0   214  23.0   NaN  1014.9   NaN

In [45]:
traffic_2022['date'] = pd.to_datetime(traffic_2022['date'], format='%m/%d/%Y')
air_quality_2022['date'] = pd.to_datetime(air_quality_2022['date'], format='%Y-%m-%d')
weather_2022['date'] = pd.to_datetime(weather_2022['date'],format='%Y-%m-%d')
merged_data_2022 = pd.merge(traffic_2022, air_quality_2022, on='date', how='inner')
merged_data_2022 = pd.merge(merged_data_2022, weather_2022, on='date', how='inner')

traffic_2023['date'] = pd.to_datetime(traffic_2023['date'], format='%m/%d/%Y')
air_quality_2023['date'] = pd.to_datetime(air_quality_2023['date'], format='%Y-%m-%d')
weather_2023['date'] = pd.to_datetime(weather_2023['date'],format='%Y-%m-%d')
merged_data_2023 = pd.merge(traffic_2023, air_quality_2023, on='date', how='inner')
merged_data_2023 = pd.merge(merged_data_2023, weather_2023, on='date', how='inner')

traffic_2024['date'] = pd.to_datetime(traffic_2024['date'], format='%m/%d/%Y')
air_quality_2024['date'] = pd.to_datetime(air_quality_2024['date'], format='%Y-%m-%d')
weather_2024['date'] = pd.to_datetime(weather_2024['date'],format='%Y-%m-%d')
merged_data_2024 = pd.merge(traffic_2024, air_quality_2024, on='date', how='inner')
merged_data_2024 = pd.merge(merged_data_2024, weather_2024, on='date', how='inner')

In [47]:
nan_count_2022 = merged_data_2022.isna().sum()
nan_count_2023 = merged_data_2023.isna().sum()
nan_count_2024 = merged_data_2024.isna().sum()

nan_counts = pd.DataFrame({
    '2022': nan_count_2022,
    '2023': nan_count_2023,
    '2024': nan_count_2024
})

In [49]:
nan_counts

                    2022   2023   2024
Air_Quality_Index    0.0    0.0    0.0
Traffic_Volume       0.0    0.0    0.0
Unnamed: 2         365.0    NaN  152.0
Unnamed: 2_x         NaN  365.0    NaN
Unnamed: 2_y         NaN  365.0    NaN
Unnamed: 3         365.0  365.0  152.0
Unnamed: 4         365.0  365.0  152.0
Unnamed: 5         365.0  365.0  152.0
Unnamed: 6         358.0  358.0  152.0
Unnamed: 7         359.0  359.0  145.0
Unnamed: 8           NaN    NaN  146.0
date                 0.0    0.0    0.0
prcp                 0.0    0.0    0.0
pres                 0.0    0.0    0.0
snow                 0.0    0.0    0.0
tavg                 0.0    0.0    0.0
tmax                 0.0    0.0    0.0
tmin                 0.0    0.0    0.0
tsun               365.0  365.0  152.0
wdir                 0.0    0.0    0.0
wpgt               365.0  365.0  152.0
wspd                 0.0    0.0    0.0

In [51]:
cleaned_data_2022 = merged_data_2022.dropna(axis=1)

cleaned_data_2023 = merged_data_2023.dropna(axis=1)

cleaned_data_2024 = merged_data_2024.dropna(axis=1)

In [53]:
cleaned_data_2022.head()

,date,Traffic_Volume,Air_Quality_Index,tavg,tmin,tmax,prcp,snow,wdir,wspd,pres
0,2022-01-01,38212,Good,11.1,3.3,16.1,10.9,0,350,16.6,1004.5
1,2022-01-02,37989,Good,0.5,-4.9,3.3,0.5,0,4,18.7,1016.7
2,2022-01-03,38157,Good,-3.9,-6.0,-0.5,0.0,0,294,11.2,1028.3
3,2022-01-04,37222,Good,-2.5,-6.0,5.0,0.0,0,172,20.2,1020.1
4,2022-01-05,37754,Good,1.4,-9.9,4.4,0.0,0,252,34.6,1010.0

In [55]:
cleaned_data_2023.head()

,date,Traffic_Volume,Air_Quality_Index,tavg,tmin,tmax,prcp,snow,wdir,wspd,pres
0,2023-01-01,38779,Good,7.3,4.4,11.1,0.0,0,198,12.6,1015.1
1,2023-01-02,38298,Good,10.3,8.9,13.9,0.3,0,101,8.6,1015.6
2,2023-01-03,38353,Good,14.9,13.3,17.2,21.6,0,181,18.7,1005.5
3,2023-01-04,38890,Good,10.2,2.8,15.0,0.0,0,252,19.8,1008.3
4,2023-01-05,38374,Good,2.9,0.6,4.4,0.3,0,230,19.8,1014.3

In [57]:
cleaned_data_2024.head()

,date,Traffic_Volume,Air_Quality_Index,tavg,tmin,tmax,prcp,snow,wdir,wspd,pres
0,2024-01-01,40734,Good,0.8,0.0,3.3,0.0,0,299,15.5,1024.1
1,2024-01-02,40242,Good,-0.1,-3.2,1.1,0.0,0,239,19.1,1024.8
2,2024-01-03,39737,Good,-1.7,-4.3,1.1,0.0,0,269,13.7,1019.5
3,2024-01-04,39888,Good,0.4,-3.8,1.7,0.0,0,340,10.1,1026.2
4,2024-01-05,40137,Good,-2.1,-6.0,3.3,0.0,0,108,12.2,1023.0

In [59]:
all_cleaned_data = pd.concat([cleaned_data_2022, cleaned_data_2023, cleaned_data_2024])

all_cleaned_data_sorted = all_cleaned_data.sort_values(by='date')

all_cleaned_data_sorted.shape

(882, 11)

In [61]:
range_data = all_cleaned_data_sorted.agg(['min', 'max'])
range_data

,date,Traffic_Volume,Air_Quality_Index,tavg,tmin,tmax,prcp,snow,wdir,wspd,pres
min,2022-01-01,36906,Good,-19.4,-22.7,-17.1,0.0,0,0,3.6,991.0
max,2024-05-31,41210,Unhealthy,30.4,26.1,37.2,56.9,180,359,43.6,1039.2

In [63]:
unique_values_count = all_cleaned_data_sorted.nunique()
unique_values_count

date                 882
Traffic_Volume       771
Air_Quality_Index      5
tavg                 323
tmin                  82
tmax                  84
prcp                  96
snow                   8
wdir                 321
wspd                  84
pres                 265
dtype: int64

In [65]:
features = all_cleaned_data_sorted.drop(columns=['Air_Quality_Index'])
target = all_cleaned_data_sorted['Air_Quality_Index']

In [67]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder


numeric_features = features.select_dtypes(include=['float64', 'int64'])
scaler = StandardScaler()
normalized_numeric_features = pd.DataFrame(scaler.fit_transform(numeric_features), columns=numeric_features.columns)

In [69]:
normalized_numeric_features.agg(['min', 'max'])

,Traffic_Volume,tavg,tmin,tmax,prcp,snow,wdir,wspd,pres
min,-1.581714,-3.183154,-3.077758,-3.290140,-0.378236,-0.137643,-2.051527,-2.050825,-3.854707
max,2.717804,1.847758,1.983415,1.871376,7.799465,13.960551,1.697074,4.669195,3.401923

In [71]:
non_numeric_features = features.select_dtypes(exclude=['float64', 'int64'])
final_features = pd.concat([normalized_numeric_features, non_numeric_features.reset_index(drop=True)], axis=1)

In [73]:
final_features

,Traffic_Volume,tavg,tmin,tmax,prcp,snow,wdir,wspd,pres,date
0,-0.277074,-0.101973,-0.381232,-0.134296,1.188318,-0.137643,1.603098,0.133181,-1.822248,2022-01-01
1,-0.499842,-1.172810,-1.231675,-1.351007,-0.306376,-0.137643,-2.009760,0.485982,0.014492,2022-01-02
2,-0.332017,-1.617308,-1.345759,-1.712218,-0.378236,-0.137643,1.018358,-0.774021,1.760901,2022-01-03
3,-1.266043,-1.475877,-1.345759,-1.189412,-0.378236,-0.137643,-0.255540,0.737983,0.526370,2022-01-04
4,-0.734597,-1.081889,-1.750238,-1.246446,-0.378236,-0.137643,0.579803,3.157190,-0.994210,2022-01-05
...,...,...,...,...,...,...,...,...,...,...
877,1.530042,0.726410,0.946289,0.550104,-0.335120,-0.137643,0.611129,1.275585,-1.566309,2024-05-27
878,1.462113,0.675899,0.655894,0.654665,-0.306376,-0.137643,0.861731,0.133181,-0.361889,2024-05-28
879,2.159386,0.473854,0.541810,0.502577,-0.378236,-0.137643,1.237636,0.183582,0.360763,2024-05-29
880,2.273267,0.514263,0.313642,0.607138,-0.378236,-0.137643,-1.967993,-1.513224,0.752199,2024-05-30
881,0.703903,0.776921,0.718121,0.654665,-0.378236,-0.137643,-0.777629,-0.236420,0.887696,2024-05-31

In [75]:
final_features.agg(['min', 'max'])

,Traffic_Volume,tavg,tmin,tmax,prcp,snow,wdir,wspd,pres,date
min,-1.581714,-3.183154,-3.077758,-3.290140,-0.378236,-0.137643,-2.051527,-2.050825,-3.854707,2022-01-01
max,2.717804,1.847758,1.983415,1.871376,7.799465,13.960551,1.697074,4.669195,3.401923,2024-05-31

In [77]:
import re
from sklearn.preprocessing import LabelEncoder
import pandas as pd

class_labels = ['Good', 'Moderate', 'Poor', 'Severe', 'Unhealthy']

label_encoder = LabelEncoder()

air_quality_index = all_cleaned_data_sorted['Air_Quality_Index']

air_quality_index_simplified = air_quality_index.apply(
    lambda x: next((label for label in class_labels if re.search(label, x)), None)
)

air_quality_index_label = label_encoder.fit_transform(air_quality_index_simplified)

label_mapping_legend = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))

final_features = pd.concat([final_features, pd.DataFrame(air_quality_index_label, columns=['Air_Quality_Index_Label'])], axis=1)

label_mapping_legend, final_features.head()

({'Good': 0, 'Moderate': 1, 'Poor': 2, 'Severe': 3, 'Unhealthy': 4},
    Traffic_Volume      tavg      tmin      tmax      prcp      snow      wdir  \
 0       -0.277074 -0.101973 -0.381232 -0.134296  1.188318 -0.137643  1.603098
 1       -0.499842 -1.172810 -1.231675 -1.351007 -0.306376 -0.137643 -2.009760
 2       -0.332017 -1.617308 -1.345759 -1.712218 -0.378236 -0.137643  1.018358
 3       -1.266043 -1.475877 -1.345759 -1.189412 -0.378236 -0.137643 -0.255540
 4       -0.734597 -1.081889 -1.750238 -1.246446 -0.378236 -0.137643  0.579803

        wspd      pres       date  Air_Quality_Index_Label
 0  0.133181 -1.822248 2022-01-01                        0
 1  0.485982  0.014492 2022-01-02                        0
 2 -0.774021  1.760901 2022-01-03                        0
 3  0.737983  0.526370 2022-01-04                        0
 4  3.157190 -0.994210 2022-01-05                        0  )

In [79]:
final_features

,Traffic_Volume,tavg,tmin,tmax,prcp,snow,wdir,wspd,pres,date,Air_Quality_Index_Label
0,-0.277074,-0.101973,-0.381232,-0.134296,1.188318,-0.137643,1.603098,0.133181,-1.822248,2022-01-01,0
1,-0.499842,-1.172810,-1.231675,-1.351007,-0.306376,-0.137643,-2.009760,0.485982,0.014492,2022-01-02,0
2,-0.332017,-1.617308,-1.345759,-1.712218,-0.378236,-0.137643,1.018358,-0.774021,1.760901,2022-01-03,0
3,-1.266043,-1.475877,-1.345759,-1.189412,-0.378236,-0.137643,-0.255540,0.737983,0.526370,2022-01-04,0
4,-0.734597,-1.081889,-1.750238,-1.246446,-0.378236,-0.137643,0.579803,3.157190,-0.994210,2022-01-05,0
...,...,...,...,...,...,...,...,...,...,...,...
877,1.530042,0.726410,0.946289,0.550104,-0.335120,-0.137643,0.611129,1.275585,-1.566309,2024-05-27,0
878,1.462113,0.675899,0.655894,0.654665,-0.306376,-0.137643,0.861731,0.133181,-0.361889,2024-05-28,0
879,2.159386,0.473854,0.541810,0.502577,-0.378236,-0.137643,1.237636,0.183582,0.360763,2024-05-29,0
880,2.273267,0.514263,0.313642,0.607138,-0.378236,-0.137643,-1.967993,-1.513224,0.752199,2024-05-30,0
881,0.703903,0.776921,0.718121,0.654665,-0.378236,-0.137643,-0.777629,-0.236420,0.887696,2024-05-31,0

In [81]:
target_encoded = final_features["Air_Quality_Index_Label"]
final_features = final_features.drop('Air_Quality_Index_Label', axis=1)

In [83]:
final_features['date'] = pd.to_datetime(final_features['date'])
final_features['year'] = final_features['date'].dt.year.astype('int64')
final_features['month'] = final_features['date'].dt.month.astype('int64')
final_features['day_of_week'] = final_features['date'].dt.dayofweek.astype('int64')  #Monday=0, Sunday=6
final_features['week_number'] = final_features['date'].dt.isocalendar().week.astype('int64')  #Week number of the year

In [85]:
final_features

,Traffic_Volume,tavg,tmin,tmax,prcp,snow,wdir,wspd,pres,date,year,month,day_of_week,week_number
0,-0.277074,-0.101973,-0.381232,-0.134296,1.188318,-0.137643,1.603098,0.133181,-1.822248,2022-01-01,2022,1,5,52
1,-0.499842,-1.172810,-1.231675,-1.351007,-0.306376,-0.137643,-2.009760,0.485982,0.014492,2022-01-02,2022,1,6,52
2,-0.332017,-1.617308,-1.345759,-1.712218,-0.378236,-0.137643,1.018358,-0.774021,1.760901,2022-01-03,2022,1,0,1
3,-1.266043,-1.475877,-1.345759,-1.189412,-0.378236,-0.137643,-0.255540,0.737983,0.526370,2022-01-04,2022,1,1,1
4,-0.734597,-1.081889,-1.750238,-1.246446,-0.378236,-0.137643,0.579803,3.157190,-0.994210,2022-01-05,2022,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,1.530042,0.726410,0.946289,0.550104,-0.335120,-0.137643,0.611129,1.275585,-1.566309,2024-05-27,2024,5,0,22
878,1.462113,0.675899,0.655894,0.654665,-0.306376,-0.137643,0.861731,0.133181,-0.361889,2024-05-28,2024,5,1,22
879,2.159386,0.473854,0.541810,0.502577,-0.378236,-0.137643,1.237636,0.183582,0.360763,2024-05-29,2024,5,2,22
880,2.273267,0.514263,0.313642,0.607138,-0.378236,-0.137643,-1.967993,-1.513224,0.752199,2024-05-30,2024,5,3,22
881,0.703903,0.776921,0.718121,0.654665,-0.378236,-0.137643,-0.777629,-0.236420,0.887696,2024-05-31,2024,5,4,22

In [87]:
!pip install holidays
!pip install workalendar

Requirement already satisfied: holidays in /opt/anaconda3/lib/python3.12/site-packages (0.58)
Requirement already satisfied: python-dateutil in /opt/anaconda3/lib/python3.12/site-packages (from holidays) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil->holidays) (1.16.0)
Requirement already satisfied: workalendar in /opt/anaconda3/lib/python3.12/site-packages (17.0.0)
Requirement already satisfied: python-dateutil in /opt/anaconda3/lib/python3.12/site-packages (from workalendar) (2.9.0.post0)
Requirement already satisfied: lunardate in /opt/anaconda3/lib/python3.12/site-packages (from workalendar) (0.2.2)
Requirement already satisfied: convertdate in /opt/anaconda3/lib/python3.12/site-packages (from workalendar) (2.4.0)
Requirement already satisfied: pyluach in /opt/anaconda3/lib/python3.12/site-packages (from workalendar) (2.2.0)
Requirement already satisfied: pymeeus<=1,>=0.3.13 in /opt/anaconda3/lib/python3.12/site-packages (from convertdate->workalendar) (0.5.12)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil->workalendar) (1.16.0)

In [89]:
import numpy as np
import holidays
from workalendar.usa import UnitedStates

final_features['date'] = pd.to_datetime(final_features['date'])

us_holidays = holidays.US()
from datetime import timedelta

def is_observed_holiday(date):
    if date in us_holidays:
        return 1
    
    if (date.weekday() == 0) and (date - timedelta(days=1)) in us_holidays:  
        return 1
    
    if (date.weekday() == 4) and (date + timedelta(days=1)) in us_holidays:
        return 1
    
    return 0

final_features['is_holiday'] = final_features['date'].apply(lambda x: is_observed_holiday(x))

cal = UnitedStates()
final_features['is_school_break'] = final_features['date'].apply(lambda x: 1 if cal.is_working_day(x) == False else 0)

from datetime import date

def is_between(date, start_month, start_day, end_month, end_day):
    start = date.replace(month=start_month, day=start_day)
    end = date.replace(month=end_month, day=end_day)
    if start <= end:
        return start <= date <= end
    else: 
        return date >= start or date <= end

final_features['is_winter_break'] = final_features['date'].apply(lambda x: 1 if is_between(x, 12, 20, 1, 5) else 0)
final_features['is_summer_break'] = final_features['date'].apply(lambda x: 1 if is_between(x, 6, 1, 8, 31) else 0)
final_features['is_weekend'] = final_features['date'].dt.dayofweek.isin([5, 6]).astype(int)
final_features['is_break'] = final_features['date'].apply(lambda x: 1 if not cal.is_working_day(x) else 0)

def is_long_weekend(date):
    friday = date - timedelta(days=(date.weekday() - 4) % 7)
    monday = date + timedelta(days=(7 - date.weekday()) % 7)
    
    if not cal.is_working_day(friday) or not cal.is_working_day(monday):
        return 1 if date in [friday, friday + timedelta(days=1), friday + timedelta(days=2),
                             monday - timedelta(days=2), monday - timedelta(days=1), monday] else 0
    else:
        return 0 
        
final_features['is_long_weekend'] = final_features['date'].apply(is_long_weekend)


def days_to_break(date):
    current_year = date.year
    next_year = current_year + 1
    summer_start = date.replace(month=6, day=1)
    summer_end = date.replace(month=8, day=31)
    winter_start = date.replace(month=12, day=20)
    winter_end = date.replace(year=next_year, month=1, day=5)

    if date < summer_start:
        days_to_summer = (summer_start - date).days
    elif date > summer_end:
        days_to_summer = (summer_start.replace(year=next_year) - date).days
    else:
        days_to_summer = 0  

    if date < winter_start:
        days_to_winter = (winter_start - date).days
    elif date > winter_end:
        days_to_winter = (winter_start.replace(year=next_year) - date).days
    else:
        days_to_winter = 0  

    return min(days_to_summer, days_to_winter)

final_features['days_to_break'] = final_features['date'].apply(days_to_break)
final_features['break_proximity'] = np.exp(-final_features['days_to_break'] / 30)  # exponential decay

In [91]:
final_features.head(200)

,Traffic_Volume,tavg,tmin,tmax,prcp,snow,wdir,wspd,pres,date,...,week_number,is_holiday,is_school_break,is_winter_break,is_summer_break,is_weekend,is_break,is_long_weekend,days_to_break,break_proximity
0,-0.277074,-0.101973,-0.381232,-0.134296,1.188318,-0.137643,1.603098,0.133181,-1.822248,2022-01-01,...,52,1,1,1,0,1,1,1,151,0.006517
1,-0.499842,-1.172810,-1.231675,-1.351007,-0.306376,-0.137643,-2.009760,0.485982,0.014492,2022-01-02,...,52,0,1,1,0,1,1,1,150,0.006738
2,-0.332017,-1.617308,-1.345759,-1.712218,-0.378236,-0.137643,1.018358,-0.774021,1.760901,2022-01-03,...,1,0,0,1,0,0,0,1,149,0.006966
3,-1.266043,-1.475877,-1.345759,-1.189412,-0.378236,-0.137643,-0.255540,0.737983,0.526370,2022-01-04,...,1,0,0,1,0,0,0,0,148,0.007202
4,-0.734597,-1.081889,-1.750238,-1.246446,-0.378236,-0.137643,0.579803,3.157190,-0.994210,2022-01-05,...,1,0,0,1,0,0,0,0,147,0.007447
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,-0.601735,1.110295,1.174457,0.977854,-0.263260,-0.137643,-1.602530,-1.378823,0.466149,2022-07-15,...,28,0,0,0,1,0,0,0,0,1.000000
196,-0.741590,1.342646,1.412995,1.453132,-0.119539,-0.137643,-0.109355,0.435582,-0.361889,2022-07-16,...,28,0,1,0,1,1,1,0,0,1.000000
197,-0.568770,1.251726,1.412995,0.768732,1.993154,-0.137643,0.099481,-0.169220,-0.828602,2022-07-17,...,28,0,1,0,1,1,1,0,0,1.000000
198,-1.491807,1.069886,1.350768,1.129943,0.282879,-0.137643,0.788639,-1.076422,-0.723215,2022-07-18,...,29,0,0,0,1,0,0,0,0,1.000000
199,-0.889435,1.362851,1.412995,1.348571,-0.378236,-0.137643,0.078598,-0.841222,-0.723215,2022-07-19,...,29,0,0,0,1,0,0,0,0,1.000000

In [93]:
def add_cyclical_features(df, col_name, period):
    df[f'{col_name}_sin'] = np.sin(2 * np.pi * df[col_name] / period)
    df[f'{col_name}_cos'] = np.cos(2 * np.pi * df[col_name] / period)
    return df

final_features['date'] = pd.to_datetime(final_features['date'])

#cyclical components
final_features['month'] = final_features['date'].dt.month
final_features['quarter'] = final_features['date'].dt.quarter
final_features['four_month'] = (final_features['month'] - 1) // 4 + 1
final_features['half_year'] = (final_features['month'] - 1) // 6 + 1

final_features = add_cyclical_features(final_features, 'month', 12)
final_features = add_cyclical_features(final_features, 'week_number', 52)
final_features = add_cyclical_features(final_features, 'quarter', 4)
final_features = add_cyclical_features(final_features, 'four_month', 3)
final_features = add_cyclical_features(final_features, 'half_year', 2)

final_features.head()

,Traffic_Volume,tavg,tmin,tmax,prcp,snow,wdir,wspd,pres,date,...,month_sin,month_cos,week_number_sin,week_number_cos,quarter_sin,quarter_cos,four_month_sin,four_month_cos,half_year_sin,half_year_cos
0,-0.277074,-0.101973,-0.381232,-0.134296,1.188318,-0.137643,1.603098,0.133181,-1.822248,2022-01-01,...,0.5,0.866025,6.432491e-16,1.000000,1.0,6.123234e-17,0.866025,-0.5,1.224647e-16,-1.0
1,-0.499842,-1.172810,-1.231675,-1.351007,-0.306376,-0.137643,-2.009760,0.485982,0.014492,2022-01-02,...,0.5,0.866025,6.432491e-16,1.000000,1.0,6.123234e-17,0.866025,-0.5,1.224647e-16,-1.0
2,-0.332017,-1.617308,-1.345759,-1.712218,-0.378236,-0.137643,1.018358,-0.774021,1.760901,2022-01-03,...,0.5,0.866025,1.205367e-01,0.992709,1.0,6.123234e-17,0.866025,-0.5,1.224647e-16,-1.0
3,-1.266043,-1.475877,-1.345759,-1.189412,-0.378236,-0.137643,-0.255540,0.737983,0.526370,2022-01-04,...,0.5,0.866025,1.205367e-01,0.992709,1.0,6.123234e-17,0.866025,-0.5,1.224647e-16,-1.0
4,-0.734597,-1.081889,-1.750238,-1.246446,-0.378236,-0.137643,0.579803,3.157190,-0.994210,2022-01-05,...,0.5,0.866025,1.205367e-01,0.992709,1.0,6.123234e-17,0.866025,-0.5,1.224647e-16,-1.0

In [95]:
final_features = final_features.drop(columns=['date'])

In [97]:
final_features.shape

(882, 35)

In [99]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(final_features, target_encoded, test_size=0.2, shuffle=False)
print("X_train shape:", X_train.shape)
print("X_val shape:", X_val.shape)
print("y_train shape:", y_train.shape)
print("y_valt shape:", y_val.shape)

X_train shape: (705, 35)
X_val shape: (177, 35)
y_train shape: (705,)
y_valt shape: (177,)

In [101]:
X_train.to_csv('X_train.csv', index=False)
X_val.to_csv('X_val.csv', index=False)
y_train.to_csv('y_train.csv', index=False)
y_val.to_csv('y_val.csv', index=False)

In [103]:
X_train

,Traffic_Volume,tavg,tmin,tmax,prcp,snow,wdir,wspd,pres,year,...,month_sin,month_cos,week_number_sin,week_number_cos,quarter_sin,quarter_cos,four_month_sin,four_month_cos,half_year_sin,half_year_cos
0,-0.277074,-0.101973,-0.381232,-0.134296,1.188318,-0.137643,1.603098,0.133181,-1.822248,2022,...,5.000000e-01,0.866025,6.432491e-16,1.000000,1.000000e+00,6.123234e-17,8.660254e-01,-0.5,1.224647e-16,-1.0
1,-0.499842,-1.172810,-1.231675,-1.351007,-0.306376,-0.137643,-2.009760,0.485982,0.014492,2022,...,5.000000e-01,0.866025,6.432491e-16,1.000000,1.000000e+00,6.123234e-17,8.660254e-01,-0.5,1.224647e-16,-1.0
2,-0.332017,-1.617308,-1.345759,-1.712218,-0.378236,-0.137643,1.018358,-0.774021,1.760901,2022,...,5.000000e-01,0.866025,1.205367e-01,0.992709,1.000000e+00,6.123234e-17,8.660254e-01,-0.5,1.224647e-16,-1.0
3,-1.266043,-1.475877,-1.345759,-1.189412,-0.378236,-0.137643,-0.255540,0.737983,0.526370,2022,...,5.000000e-01,0.866025,1.205367e-01,0.992709,1.000000e+00,6.123234e-17,8.660254e-01,-0.5,1.224647e-16,-1.0
4,-0.734597,-1.081889,-1.750238,-1.246446,-0.378236,-0.137643,0.579803,3.157190,-0.994210,2022,...,5.000000e-01,0.866025,1.205367e-01,0.992709,1.000000e+00,6.123234e-17,8.660254e-01,-0.5,1.224647e-16,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,-0.533806,-0.374733,-0.090837,-0.714134,-0.378236,-0.137643,0.600687,-1.026022,-0.392000,2023,...,-2.449294e-16,1.000000,-4.647232e-01,0.885456,-2.449294e-16,1.000000e+00,-2.449294e-16,1.0,-2.449294e-16,1.0
701,0.418201,-0.647494,-0.661256,-1.084851,-0.191399,-0.137643,0.506711,-0.051619,-1.039375,2023,...,-2.449294e-16,1.000000,-4.647232e-01,0.885456,-2.449294e-16,1.000000e+00,-2.449294e-16,1.0,-2.449294e-16,1.0
702,-1.169144,-0.950560,-0.723483,-1.027818,-0.378236,-0.137643,1.436030,-1.378823,-0.211337,2023,...,-2.449294e-16,1.000000,-3.546049e-01,0.935016,-2.449294e-16,1.000000e+00,-2.449294e-16,1.0,-2.449294e-16,1.0
703,-1.088228,-0.869743,-0.547172,-1.084851,-0.263260,-0.137643,0.600687,-0.354020,0.104823,2023,...,-2.449294e-16,1.000000,-3.546049e-01,0.935016,-2.449294e-16,1.000000e+00,-2.449294e-16,1.0,-2.449294e-16,1.0
704,-0.875450,-0.990969,-0.827196,-1.351007,-0.378236,-0.137643,0.746872,-0.236420,1.279133,2023,...,-2.449294e-16,1.000000,-3.546049e-01,0.935016,-2.449294e-16,1.000000e+00,-2.449294e-16,1.0,-2.449294e-16,1.0

In [105]:
X_train.columns

Index(['Traffic_Volume', 'tavg', 'tmin', 'tmax', 'prcp', 'snow', 'wdir',
       'wspd', 'pres', 'year', 'month', 'day_of_week', 'week_number',
       'is_holiday', 'is_school_break', 'is_winter_break', 'is_summer_break',
       'is_weekend', 'is_break', 'is_long_weekend', 'days_to_break',
       'break_proximity', 'quarter', 'four_month', 'half_year', 'month_sin',
       'month_cos', 'week_number_sin', 'week_number_cos', 'quarter_sin',
       'quarter_cos', 'four_month_sin', 'four_month_cos', 'half_year_sin',
       'half_year_cos'],
      dtype='object')

In [107]:
import torch
import torch.nn as nn
import torch.optim as optim

X_train_numeric = X_train.select_dtypes(include=[float, int])
X_val_numeric = X_val.select_dtypes(include=[float, int])

X_train_tensor = torch.tensor(X_train_numeric.values, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32)  
X_val_tensor = torch.tensor(X_val_numeric.values, dtype=torch.float32)
y_val_tensor = torch.tensor(y_val.values, dtype=torch.float32)

In [111]:
from torch.utils.data import DataLoader, TensorDataset

In [113]:
y_train_labels = y_train_tensor
y_val_labels = y_val_tensor

sequence_length = 5

def create_sequences(X, y_labels, seq_length):
    sequences = []
    targets = []
    for i in range(seq_length, len(X)):
        X_seq = X[i-seq_length:i]  
        y_seq = y_labels[i]        
        sequences.append(X_seq)
        targets.append(y_seq)
    return torch.stack(sequences), torch.stack(targets).long()

In [115]:
X_train_sequences, y_train_sequences = create_sequences(X_train_tensor, y_train_labels, sequence_length)
X_val_sequences, y_val_sequences = create_sequences(X_val_tensor, y_val_labels, sequence_length)

In [117]:
class TimeSeriesDataset(torch.utils.data.Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
    def __len__(self):
        return len(self.X)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [119]:
batch_size = 32
train_dataset = TimeSeriesDataset(X_train_sequences, y_train_sequences)
val_dataset = TimeSeriesDataset(X_val_sequences, y_val_sequences)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

In [121]:
class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes, dropout=0.5):
        super(LSTMModel, self).__init__()
        self.lstm = nn.LSTM(
            input_size, hidden_size, num_layers=num_layers, 
            batch_first=True, dropout=dropout
        )
        self.fc1 = nn.Linear(hidden_size, hidden_size // 2)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(dropout)
        self.fc2 = nn.Linear(hidden_size // 2, num_classes)
    def forward(self, x):
        out, _ = self.lstm(x)
        out = out[:, -1, :]
        out = self.fc1(out)
        out = self.relu(out)
        out = self.dropout(out)
        out = self.fc2(out)
        return out

In [123]:
input_size = X_train_sequences.shape[2]
hidden_size = 512
num_layers = 10 
num_epochs = 70
num_classes = 5

In [125]:
model = LSTMModel(input_size, hidden_size, num_layers, num_classes)
criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=0.0001, weight_decay=1e-7)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

LSTMModel(
  (lstm): LSTM(35, 512, num_layers=10, batch_first=True, dropout=0.5)
  (fc1): Linear(in_features=512, out_features=256, bias=True)
  (relu): ReLU()
  (dropout): Dropout(p=0.5, inplace=False)
  (fc2): Linear(in_features=256, out_features=5, bias=True)
)

In [127]:
# scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=10)

# scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, 'min', patience=5)

scheduler = optim.lr_scheduler.OneCycleLR(
    optimizer, max_lr=0.001, steps_per_epoch=len(train_loader), epochs=num_epochs
)

# scheduler = optim.lr_scheduler.CyclicLR(
#     optimizer, base_lr=0.0001, max_lr=0.01, step_size_up=5, mode='triangular2'
# )

# optimizer = optim.AdamW(model.parameters(), lr=0.001, weight_decay=1e-5)

In [129]:
early_stop_patience = 10
best_val_loss = float('inf')
epochs_no_improve = 0

for epoch in range(num_epochs):
    model.train()
    train_loss = 0
    correct = 0
    total = 0

    for X_batch, y_batch in train_loader:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)

        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        train_loss += loss.item() * X_batch.size(0)
        _, predicted = torch.max(outputs.data, 1)
        total += y_batch.size(0)
        correct += (predicted == y_batch).sum().item()

    scheduler.step()

    train_loss /= len(train_loader.dataset)
    train_accuracy = 100 * correct / total
    
    model.eval()
    val_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():
        for X_batch, y_batch in val_loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)
            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)
            val_loss += loss.item() * X_batch.size(0)
            _, predicted = torch.max(outputs.data, 1)
            total += y_batch.size(0)
            correct += (predicted == y_batch).sum().item()

    val_loss /= len(val_loader.dataset)
    val_accuracy = 100 * correct / total

    print(f'Epoch [{epoch+1}/{num_epochs}], '
          f'Train Loss: {train_loss:.4f}, Train Acc: {train_accuracy:.2f}%, '
          f'Val Loss: {val_loss:.4f}, Val Acc: {val_accuracy:.2f}%')

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        epochs_no_improve = 0
        best_model = model.state_dict()
    else:
        epochs_no_improve += 1
        if epochs_no_improve == early_stop_patience:
            print("Early stopping!")
            model.load_state_dict(best_model)
            break

Epoch [1/70], Train Loss: 1.6427, Train Acc: 1.86%, Val Loss: 1.6094, Val Acc: 0.58%
Epoch [2/70], Train Loss: 1.5695, Train Acc: 55.29%, Val Loss: 1.5093, Val Acc: 99.42%
Epoch [3/70], Train Loss: 1.3963, Train Acc: 95.57%, Val Loss: 1.1115, Val Acc: 99.42%
Epoch [4/70], Train Loss: 0.6229, Train Acc: 95.57%, Val Loss: 0.0483, Val Acc: 99.42%
Epoch [5/70], Train Loss: 0.2662, Train Acc: 95.57%, Val Loss: 0.0416, Val Acc: 99.42%
Epoch [6/70], Train Loss: 0.2770, Train Acc: 95.57%, Val Loss: 0.0412, Val Acc: 99.42%
Epoch [7/70], Train Loss: 0.2328, Train Acc: 95.57%, Val Loss: 0.0518, Val Acc: 99.42%
Epoch [8/70], Train Loss: 0.2214, Train Acc: 95.57%, Val Loss: 0.0608, Val Acc: 99.42%
Epoch [9/70], Train Loss: 0.2222, Train Acc: 95.57%, Val Loss: 0.0534, Val Acc: 99.42%
Epoch [10/70], Train Loss: 0.2265, Train Acc: 95.57%, Val Loss: 0.0491, Val Acc: 99.42%
Epoch [11/70], Train Loss: 0.2200, Train Acc: 95.57%, Val Loss: 0.0512, Val Acc: 99.42%
Epoch [12/70], Train Loss: 0.2192, Train Acc: 95.57%, Val Loss: 0.0489, Val Acc: 99.42%
Epoch [13/70], Train Loss: 0.2177, Train Acc: 95.57%, Val Loss: 0.0522, Val Acc: 99.42%
Epoch [14/70], Train Loss: 0.2163, Train Acc: 95.57%, Val Loss: 0.0536, Val Acc: 99.42%
Epoch [15/70], Train Loss: 0.2226, Train Acc: 95.57%, Val Loss: 0.0503, Val Acc: 99.42%
Epoch [16/70], Train Loss: 0.2251, Train Acc: 95.57%, Val Loss: 0.0496, Val Acc: 99.42%
Early stopping!

In [130]:
torch.save(model.state_dict(), 'best_lstm_model.pth')

## TESTING

In [146]:
merged_data_2024_test_cleaned = pd.read_csv('X_test.csv')

In [148]:
X_test_numeric = merged_data_2024_test_cleaned.select_dtypes(include=[float, int])


X_test_tensor = torch.tensor(X_test_numeric.values, dtype=torch.float32)

def create_sequences_test(X, seq_length):
    sequences = []
    for i in range(seq_length, len(X)):
        X_seq = X[i-seq_length:i]
        sequences.append(X_seq)
    return torch.stack(sequences)

sequence_length = 5
X_test_sequences = create_sequences_test(X_test_tensor, sequence_length)

test_dataset = torch.utils.data.TensorDataset(X_test_sequences)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=32, shuffle=False)

In [150]:
model.load_state_dict(torch.load('best_lstm_model.pth', weights_only=True))

model.to(device)
model.eval()

test_predictions = []

with torch.no_grad():
    for X_batch in test_loader:
        X_batch = X_batch[0].to(device)  
        outputs = model(X_batch)         
        _, predicted = torch.max(outputs, 1)  
        test_predictions.extend(predicted.cpu().numpy())

In [152]:
label_mapping_legend = {'Good': 0, 'Moderate': 1, 'Poor': 2, 'Severe': 3, 'Unhealthy': 4}

reverse_label_mapping = {v: k for k, v in label_mapping_legend.items()}

test_predictions_labels = pd.Series([reverse_label_mapping[pred] for pred in test_predictions], name='Predicted_AQI')

ID_column = pd.Series(range(1, len(test_predictions) + 1), name='ID')

predictions_df = pd.concat([ID_column, test_predictions_labels], axis=1)

predictions_df.to_csv('test_predictions_with_labels.csv', index=False)

print(predictions_df.head())

   ID Predicted_AQI
0   1          Good
1   2          Good
2   3          Good
3   4          Good
4   5          Good

In [154]:
model.load_state_dict(torch.load('best_lstm_model.pth', weights_only=True))
model.to(device)
model.eval()

sequence_predictions = []
with torch.no_grad():
    for X_batch in test_loader:
        X_batch = X_batch[0].to(device)
        outputs = model(X_batch)
        _, predicted = torch.max(outputs, 1)
        sequence_predictions.extend(predicted.cpu().numpy())
        
individual_predictions = []
for i in range(len(X_test_numeric) - sequence_length):
    individual_predictions.append(sequence_predictions[i])

for i in range(sequence_length):
    individual_predictions.insert(0, individual_predictions[0])

label_mapping_legend = {'Good': 0, 'Moderate': 1, 'Poor': 2, 'Severe': 3, 'Unhealthy': 4}
reverse_label_mapping = {v: k for k, v in label_mapping_legend.items()}
test_predictions_labels = pd.Series([reverse_label_mapping[pred] for pred in individual_predictions], name='Predicted_AQI')
ID_column = pd.Series(range(1, len(individual_predictions) + 1), name='ID')
predictions_df = pd.concat([ID_column, test_predictions_labels], axis=1)

predictions_df.to_csv('test_predictions_with_labels.csv', index=False)
print(predictions_df.head())
print(f"Total predictions: {len(predictions_df)}")
print(f"Original data points: {len(X_test_numeric)}")

   ID Predicted_AQI
0   1          Good
1   2          Good
2   3          Good
3   4          Good
4   5          Good
Total predictions: 133
Original data points: 133